# coding: utf-8

"""
    slskd

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

from slskd.models.connection_options import ConnectionOptions  # noqa: E501


class TestConnectionOptions(unittest.TestCase):
    """ConnectionOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ConnectionOptions
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `ConnectionOptions`
        """
        model = slskd.models.connection_options.ConnectionOptions()  # noqa: E501
        if include_optional :
            return ConnectionOptions(
                timeout = slskd.models.timeout_options.TimeoutOptions(
                    connect = 1000,
                    inactivity = 1000, ),
                buffer = slskd.models.buffer_options.BufferOptions(
                    read = 1024,
                    write = 1024,
                    transfer = 81920,
                    write_queue = 5, ),
                proxy = slskd.models.proxy_options.ProxyOptions(
                    enabled = True,
                    address = '0',
                    port = 1,
                    username = '0',
                    password = '0', )
            )
        else :
            return ConnectionOptions(
        )
        """

    def testConnectionOptions(self):
        """Test ConnectionOptions"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
