# coding: utf-8

"""
    slskd

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

from slskd.models.pushbullet_options import PushbulletOptions  # noqa: E501


class TestPushbulletOptions(unittest.TestCase):
    """PushbulletOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test PushbulletOptions
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `PushbulletOptions`
        """
        model = slskd.models.pushbullet_options.PushbulletOptions()  # noqa: E501
        if include_optional :
            return PushbulletOptions(
                enabled = True,
                access_token = '',
                notification_prefix = '',
                notify_on_private_message = True,
                notify_on_room_mention = True,
                retry_attempts = 0,
                cooldown_time = 56
            )
        else :
            return PushbulletOptions(
        )
        """

    def testPushbulletOptions(self):
        """Test PushbulletOptions"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
