# coding: utf-8

"""
    slskd

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

from slskd.models.user_presence import UserPresence  # noqa: E501


class TestUserPresence(unittest.TestCase):
    """UserPresence unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserPresence(self):
        """Test UserPresence"""
        # inst = UserPresence()


if __name__ == "__main__":
    unittest.main()
