# coding: utf-8

"""
    slskd

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import slskd
from slskd.api.rooms_api import RoomsApi  # noqa: E501


class TestRoomsApi(unittest.TestCase):
    """RoomsApi unit test stubs"""

    def setUp(self):
        self.api = slskd.api.rooms_api.RoomsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_v0_rooms_available_get(self):
        """Test case for api_v0_rooms_available_get

        Gets a list of rooms from the server.  # noqa: E501
        """

    def test_api_v0_rooms_joined_get(self):
        """Test case for api_v0_rooms_joined_get

        Gets all rooms.  # noqa: E501
        """

    def test_api_v0_rooms_joined_post(self):
        """Test case for api_v0_rooms_joined_post

        Joins a room.  # noqa: E501
        """

    def test_api_v0_rooms_joined_room_name_delete(self):
        """Test case for api_v0_rooms_joined_room_name_delete

        Leaves a room.  # noqa: E501
        """

    def test_api_v0_rooms_joined_room_name_get(self):
        """Test case for api_v0_rooms_joined_room_name_get

        Gets the specified room.  # noqa: E501
        """

    def test_api_v0_rooms_joined_room_name_members_post(self):
        """Test case for api_v0_rooms_joined_room_name_members_post

        Adds a member to a private room.  # noqa: E501
        """

    def test_api_v0_rooms_joined_room_name_messages_get(self):
        """Test case for api_v0_rooms_joined_room_name_messages_get

        Gets the current list of messages for the specified room.  # noqa: E501
        """

    def test_api_v0_rooms_joined_room_name_messages_post(self):
        """Test case for api_v0_rooms_joined_room_name_messages_post

        Sends a message to the specified room.  # noqa: E501
        """

    def test_api_v0_rooms_joined_room_name_ticker_post(self):
        """Test case for api_v0_rooms_joined_room_name_ticker_post

        Sets a ticker for the specified room.  # noqa: E501
        """

    def test_api_v0_rooms_joined_room_name_users_get(self):
        """Test case for api_v0_rooms_joined_room_name_users_get

        Gets the current list of users for the specified room.  # noqa: E501
        """


if __name__ == "__main__":
    unittest.main()
