# coding: utf-8

"""
    slskd

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

from slskd.models.room_message import RoomMessage  # noqa: E501


class TestRoomMessage(unittest.TestCase):
    """RoomMessage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test RoomMessage
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `RoomMessage`
        """
        model = slskd.models.room_message.RoomMessage()  # noqa: E501
        if include_optional :
            return RoomMessage(
                timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                username = '',
                message = '',
                room_name = '',
                direction = 'Out'
            )
        else :
            return RoomMessage(
        )
        """

    def testRoomMessage(self):
        """Test RoomMessage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
