# coding: utf-8

"""
    slskd

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import slskd
from slskd.api.shares_api import SharesApi  # noqa: E501


class TestSharesApi(unittest.TestCase):
    """SharesApi unit test stubs"""

    def setUp(self):
        self.api = slskd.api.shares_api.SharesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_v0_shares_contents_get(self):
        """Test case for api_v0_shares_contents_get

        Returns a list of all shared directories and files.  # noqa: E501
        """

    def test_api_v0_shares_delete(self):
        """Test case for api_v0_shares_delete

        Cancels a share scan, if one is running.  # noqa: E501
        """

    def test_api_v0_shares_get(self):
        """Test case for api_v0_shares_get

        Gets the current list of shares.  # noqa: E501
        """

    def test_api_v0_shares_id_contents_get(self):
        """Test case for api_v0_shares_id_contents_get

        Gets the contents of the share associated with the specified <see paramref=\"id\" />.  # noqa: E501
        """

    def test_api_v0_shares_id_get(self):
        """Test case for api_v0_shares_id_get

        Gets the share associated with the specified <see paramref=\"id\" />.  # noqa: E501
        """

    def test_api_v0_shares_put(self):
        """Test case for api_v0_shares_put

        Initiates a scan of the configured shares.  # noqa: E501
        """


if __name__ == "__main__":
    unittest.main()
