# coding: utf-8

"""
    slskd

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import slskd
from slskd.api.relay_api import RelayApi  # noqa: E501


class TestRelayApi(unittest.TestCase):
    """RelayApi unit test stubs"""

    def setUp(self):
        self.api = slskd.api.relay_api.RelayApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_v0_relay_agent_delete(self):
        """Test case for api_v0_relay_agent_delete

        Disconnects from the connected controller.  # noqa: E501
        """

    def test_api_v0_relay_agent_put(self):
        """Test case for api_v0_relay_agent_put

        Connects to the configured controller.  # noqa: E501
        """

    def test_api_v0_relay_controller_downloads_token_get(self):
        """Test case for api_v0_relay_controller_downloads_token_get

        Downloads a file from the connected controller.  # noqa: E501
        """

    def test_api_v0_relay_controller_files_token_post(self):
        """Test case for api_v0_relay_controller_files_token_post

        Uploads a file to the connected controller.  # noqa: E501
        """

    def test_api_v0_relay_controller_shares_token_post(self):
        """Test case for api_v0_relay_controller_shares_token_post

        Uploads share information to the connected controller.  # noqa: E501
        """


if __name__ == "__main__":
    unittest.main()
