# coding: utf-8

"""
    slskd

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

from slskd.models.ip_address import IPAddress  # noqa: E501


class TestIPAddress(unittest.TestCase):
    """IPAddress unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test IPAddress
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `IPAddress`
        """
        model = slskd.models.ip_address.IPAddress()  # noqa: E501
        if include_optional :
            return IPAddress(
                address_family = 'Unspecified',
                scope_id = 56,
                is_ipv6_multicast = True,
                is_ipv6_link_local = True,
                is_ipv6_site_local = True,
                is_ipv6_teredo = True,
                is_ipv6_unique_local = True,
                is_ipv4_mapped_to_ipv6 = True,
                address = 56
            )
        else :
            return IPAddress(
        )
        """

    def testIPAddress(self):
        """Test IPAddress"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
