# coding: utf-8

"""
    slskd

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import slskd
from slskd.api.users_api import UsersApi  # noqa: E501


class TestUsersApi(unittest.TestCase):
    """UsersApi unit test stubs"""

    def setUp(self):
        self.api = slskd.api.users_api.UsersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_v0_users_username_browse_get(self):
        """Test case for api_v0_users_username_browse_get

        Retrieves the files shared by the specified username.  # noqa: E501
        """

    def test_api_v0_users_username_browse_status_get(self):
        """Test case for api_v0_users_username_browse_status_get

        Retrieves the status of the current browse operation for the specified username, if any.  # noqa: E501
        """

    def test_api_v0_users_username_directory_post(self):
        """Test case for api_v0_users_username_directory_post

        Retrieves the files from the specified directory from the specified username.  # noqa: E501
        """

    def test_api_v0_users_username_endpoint_get(self):
        """Test case for api_v0_users_username_endpoint_get

        Retrieves the address of the specified username.  # noqa: E501
        """

    def test_api_v0_users_username_info_get(self):
        """Test case for api_v0_users_username_info_get

        Retrieves information about the specified username.  # noqa: E501
        """

    def test_api_v0_users_username_status_get(self):
        """Test case for api_v0_users_username_status_get

        Retrieves status for the specified username.  # noqa: E501
        """


if __name__ == "__main__":
    unittest.main()
