# coding: utf-8

"""
    slskd

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

from slskd.models.room import Room  # noqa: E501


class TestRoom(unittest.TestCase):
    """Room unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Room
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `Room`
        """
        model = slskd.models.room.Room()  # noqa: E501
        if include_optional :
            return Room(
                name = '',
                is_private = True,
                operator_count = 56,
                operators = [
                    ''
                    ],
                owner = '',
                users = [
                    slskd.models.user_data.UserData(
                        average_speed = 56,
                        country_code = '',
                        directory_count = 56,
                        file_count = 56,
                        slots_free = 56,
                        status = 'Offline',
                        upload_count = 56,
                        username = '', )
                    ],
                messages = [
                    slskd.models.room_message.RoomMessage(
                        timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                        username = '',
                        message = '',
                        room_name = '',
                        direction = 'Out', )
                    ]
            )
        else :
            return Room(
        )
        """

    def testRoom(self):
        """Test Room"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
