# coding: utf-8

"""
    slskd

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

from slskd.models.integration_options import IntegrationOptions  # noqa: E501


class TestIntegrationOptions(unittest.TestCase):
    """IntegrationOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test IntegrationOptions
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `IntegrationOptions`
        """
        model = slskd.models.integration_options.IntegrationOptions()  # noqa: E501
        if include_optional :
            return IntegrationOptions(
                ftp = slskd.models.ftp_options.FtpOptions(
                    enabled = True,
                    address = '',
                    port = 1,
                    encryption_mode = '',
                    ignore_certificate_errors = True,
                    username = '',
                    password = '',
                    remote_path = '',
                    overwrite_existing = True,
                    connection_timeout = 0,
                    retry_attempts = 0, ),
                pushbullet = slskd.models.pushbullet_options.PushbulletOptions(
                    enabled = True,
                    access_token = '',
                    notification_prefix = '',
                    notify_on_private_message = True,
                    notify_on_room_mention = True,
                    retry_attempts = 0,
                    cooldown_time = 56, )
            )
        else :
            return IntegrationOptions(
        )
        """

    def testIntegrationOptions(self):
        """Test IntegrationOptions"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
