# coding: utf-8

"""
    slskd

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

from slskd.models.file import File  # noqa: E501


class TestFile(unittest.TestCase):
    """File unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test File
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `File`
        """
        model = slskd.models.file.File()  # noqa: E501
        if include_optional :
            return File(
                attribute_count = 56,
                attributes = [
                    slskd.models.file_attribute.FileAttribute(
                        type = 'BitRate',
                        value = 56, )
                    ],
                bit_depth = 56,
                bit_rate = 56,
                code = 56,
                extension = '',
                filename = '',
                is_variable_bit_rate = True,
                length = 56,
                sample_rate = 56,
                size = 56
            )
        else :
            return File(
        )
        """

    def testFile(self):
        """Test File"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
