# coding: utf-8

"""
    slskd

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

from slskd.models.server_state import ServerState  # noqa: E501


class TestServerState(unittest.TestCase):
    """ServerState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ServerState
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `ServerState`
        """
        model = slskd.models.server_state.ServerState()  # noqa: E501
        if include_optional :
            return ServerState(
                address = '',
                ip_end_point = slskd.models.ip_end_point.IPEndPoint(
                    address_family = 'Unspecified',
                    address = slskd.models.ip_address.IPAddress(
                        scope_id = 56,
                        is_ipv6_multicast = True,
                        is_ipv6_link_local = True,
                        is_ipv6_site_local = True,
                        is_ipv6_teredo = True,
                        is_ipv6_unique_local = True,
                        is_ipv4_mapped_to_ipv6 = True, ),
                    port = 56, ),
                state = 'None',
                username = '',
                is_connected = True,
                is_logged_in = True,
                is_transitioning = True
            )
        else :
            return ServerState(
        )
        """

    def testServerState(self):
        """Test ServerState"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
