# coding: utf-8

"""
    slskd

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import slskd
from slskd.api.application_api import ApplicationApi  # noqa: E501


class TestApplicationApi(unittest.TestCase):
    """ApplicationApi unit test stubs"""

    def setUp(self):
        self.api = slskd.api.application_api.ApplicationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_v0_application_delete(self):
        """Test case for api_v0_application_delete

        Stops the application.  # noqa: E501
        """

    def test_api_v0_application_dump_get(self):
        """Test case for api_v0_application_dump_get"""

    def test_api_v0_application_gc_post(self):
        """Test case for api_v0_application_gc_post

        Forces garbage collection.  # noqa: E501
        """

    def test_api_v0_application_get(self):
        """Test case for api_v0_application_get

        Gets the current state of the application.  # noqa: E501
        """

    def test_api_v0_application_put(self):
        """Test case for api_v0_application_put

        Restarts the application.  # noqa: E501
        """

    def test_api_v0_application_version_get(self):
        """Test case for api_v0_application_version_get

        Gets the current application version.  # noqa: E501
        """

    def test_api_v0_application_version_latest_get(self):
        """Test case for api_v0_application_version_latest_get

        Checks for updates.  # noqa: E501
        """


if __name__ == "__main__":
    unittest.main()
