# coding: utf-8

"""
    slskd

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

from slskd.models.user_data import UserData  # noqa: E501


class TestUserData(unittest.TestCase):
    """UserData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test UserData
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `UserData`
        """
        model = slskd.models.user_data.UserData()  # noqa: E501
        if include_optional :
            return UserData(
                average_speed = 56,
                country_code = '',
                directory_count = 56,
                file_count = 56,
                slots_free = 56,
                status = 'Offline',
                upload_count = 56,
                username = ''
            )
        else :
            return UserData(
        )
        """

    def testUserData(self):
        """Test UserData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
