# coding: utf-8

"""
    slskd

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

from slskd.models.web_options import WebOptions  # noqa: E501


class TestWebOptions(unittest.TestCase):
    """WebOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test WebOptions
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `WebOptions`
        """
        model = slskd.models.web_options.WebOptions()  # noqa: E501
        if include_optional :
            return WebOptions(
                port = 1,
                https = slskd.models.https_options.HttpsOptions(
                    disabled = True,
                    port = 1,
                    force = True,
                    certificate = slskd.models.certificate_options.CertificateOptions(
                        pfx = '',
                        password = '', ), ),
                url_base = '',
                content_path = '0',
                logging = True,
                authentication = slskd.models.web_authentication_options.WebAuthenticationOptions(
                    disabled = True,
                    username = '0',
                    password = '0',
                    jwt = slskd.models.jwt_options.JwtOptions(
                        key = '0123456789101112131415',
                        ttl = 3600, ),
                    api_keys = {
                        'key' : slskd.models.api_key_options.ApiKeyOptions(
                            key = '0123456789101112131415',
                            role = '',
                            cidr = '', )
                        }, )
            )
        else :
            return WebOptions(
        )
        """

    def testWebOptions(self):
        """Test WebOptions"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
