# coding: utf-8

"""
    slskd

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

from slskd.models.web_authentication_options import (  # noqa: E501
    WebAuthenticationOptions,
)


class TestWebAuthenticationOptions(unittest.TestCase):
    """WebAuthenticationOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test WebAuthenticationOptions
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `WebAuthenticationOptions`
        """
        model = slskd.models.web_authentication_options.WebAuthenticationOptions()  # noqa: E501
        if include_optional :
            return WebAuthenticationOptions(
                disabled = True,
                username = '0',
                password = '0',
                jwt = slskd.models.jwt_options.JwtOptions(
                    key = '0123456789101112131415',
                    ttl = 3600, ),
                api_keys = {
                    'key' : slskd.models.api_key_options.ApiKeyOptions(
                        key = '0123456789101112131415',
                        role = '',
                        cidr = '', )
                    }
            )
        else :
            return WebAuthenticationOptions(
        )
        """

    def testWebAuthenticationOptions(self):
        """Test WebAuthenticationOptions"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
