# coding: utf-8

"""
    slskd

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import slskd
from slskd.api.conversations_api import ConversationsApi  # noqa: E501


class TestConversationsApi(unittest.TestCase):
    """ConversationsApi unit test stubs"""

    def setUp(self):
        self.api = slskd.api.conversations_api.ConversationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_v0_conversations_get(self):
        """Test case for api_v0_conversations_get

        Gets all active conversations.  # noqa: E501
        """

    def test_api_v0_conversations_username_delete(self):
        """Test case for api_v0_conversations_username_delete

        Closes the conversation associated with the given username.  # noqa: E501
        """

    def test_api_v0_conversations_username_get(self):
        """Test case for api_v0_conversations_username_get

        Gets the conversation associated with the specified username.  # noqa: E501
        """

    def test_api_v0_conversations_username_id_put(self):
        """Test case for api_v0_conversations_username_id_put

        Acknowledges the given message id for the given username.  # noqa: E501
        """

    def test_api_v0_conversations_username_messages_get(self):
        """Test case for api_v0_conversations_username_messages_get"""

    def test_api_v0_conversations_username_post(self):
        """Test case for api_v0_conversations_username_post

        Sends a private message to the specified username.  # noqa: E501
        """

    def test_api_v0_conversations_username_put(self):
        """Test case for api_v0_conversations_username_put

        Acknowledges all messages from the given username.  # noqa: E501
        """


if __name__ == "__main__":
    unittest.main()
