# coding: utf-8

"""
    slskd

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

from slskd.models.user_defined_options import UserDefinedOptions  # noqa: E501


class TestUserDefinedOptions(unittest.TestCase):
    """UserDefinedOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test UserDefinedOptions
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `UserDefinedOptions`
        """
        model = slskd.models.user_defined_options.UserDefinedOptions()  # noqa: E501
        if include_optional :
            return UserDefinedOptions(
                upload = slskd.models.upload_options.UploadOptions(
                    priority = 1,
                    strategy = '',
                    slots = 1,
                    speed_limit = 1, ),
                members = [
                    ''
                    ]
            )
        else :
            return UserDefinedOptions(
        )
        """

    def testUserDefinedOptions(self):
        """Test UserDefinedOptions"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
