# coding: utf-8

"""
    slskd

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

from slskd.models.groups_options import GroupsOptions  # noqa: E501


class TestGroupsOptions(unittest.TestCase):
    """GroupsOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test GroupsOptions
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `GroupsOptions`
        """
        model = slskd.models.groups_options.GroupsOptions()  # noqa: E501
        if include_optional :
            return GroupsOptions(
                default = slskd.models.built_in_options.BuiltInOptions(
                    upload = slskd.models.upload_options.UploadOptions(
                        priority = 1,
                        strategy = '',
                        slots = 1,
                        speed_limit = 1, ), ),
                leechers = slskd.models.leecher_options.LeecherOptions(
                    thresholds = slskd.models.threshold_options.ThresholdOptions(
                        files = 1,
                        directories = 1, ),
                    upload = slskd.models.upload_options.UploadOptions(
                        priority = 1,
                        strategy = '',
                        slots = 1,
                        speed_limit = 1, ), ),
                blacklisted = slskd.models.blacklisted_options.BlacklistedOptions(
                    members = [
                        ''
                        ], ),
                user_defined = {
                    'key' : slskd.models.user_defined_options.UserDefinedOptions(
                        upload = slskd.models.upload_options.UploadOptions(
                            priority = 1,
                            strategy = '',
                            slots = 1,
                            speed_limit = 1, ),
                        members = [
                            ''
                            ], )
                    }
            )
        else :
            return GroupsOptions(
        )
        """

    def testGroupsOptions(self):
        """Test GroupsOptions"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
