# coding: utf-8

"""
    slskd

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import slskd
from slskd.api.logs_api import LogsApi  # noqa: E501


class TestLogsApi(unittest.TestCase):
    """LogsApi unit test stubs"""

    def setUp(self):
        self.api = slskd.api.logs_api.LogsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_v0_logs_get(self):
        """Test case for api_v0_logs_get

        Gets the last few application logs.  # noqa: E501
        """


if __name__ == "__main__":
    unittest.main()
