# coding: utf-8

"""
    slskd

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

from slskd.models.feature_options import FeatureOptions  # noqa: E501


class TestFeatureOptions(unittest.TestCase):
    """FeatureOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test FeatureOptions
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `FeatureOptions`
        """
        model = slskd.models.feature_options.FeatureOptions()  # noqa: E501
        if include_optional :
            return FeatureOptions(
                swagger = True
            )
        else :
            return FeatureOptions(
        )
        """

    def testFeatureOptions(self):
        """Test FeatureOptions"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
