# coding: utf-8

"""
    slskd

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

from slskd.models.transfer import Transfer  # noqa: E501


class TestTransfer(unittest.TestCase):
    """Transfer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Transfer
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `Transfer`
        """
        model = slskd.models.transfer.Transfer()  # noqa: E501
        if include_optional :
            return Transfer(
                average_speed = 1.337,
                bytes_remaining = 56,
                bytes_transferred = 56,
                direction = 'Download',
                elapsed_time = 1.337,
                end_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                filename = '',
                id = '',
                ip_end_point = slskd.models.ip_end_point.IPEndPoint(
                    address_family = 'Unspecified',
                    address = slskd.models.ip_address.IPAddress(
                        scope_id = 56,
                        is_ipv6_multicast = True,
                        is_ipv6_link_local = True,
                        is_ipv6_site_local = True,
                        is_ipv6_teredo = True,
                        is_ipv6_unique_local = True,
                        is_ipv4_mapped_to_ipv6 = True, ),
                    port = 56, ),
                percent_complete = 1.337,
                place_in_queue = 56,
                remaining_time = 1.337,
                remote_token = 56,
                size = 56,
                start_offset = 56,
                start_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                state = 'None',
                token = 56,
                username = '',
                exception = ''
            )
        else :
            return Transfer(
        )
        """

    def testTransfer(self):
        """Test Transfer"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
