# coding: utf-8

"""
    slskd

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

from slskd.models.soulseek_client_states import SoulseekClientStates  # noqa: E501


class TestSoulseekClientStates(unittest.TestCase):
    """SoulseekClientStates unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSoulseekClientStates(self):
        """Test SoulseekClientStates"""
        # inst = SoulseekClientStates()


if __name__ == "__main__":
    unittest.main()
