---
version: "2"
services:
  slskd:
    image: slskd/slskd
    container_name: slskd
    command: --swagger
    ports:
      - "5030:5030"
      - "5031:5031"
      - "50300:50300"
    volumes:
      - "$HOME/slskd:/app"
    restart: always
