# coding: utf-8

"""
    slskd

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import json
import re  # noqa: F401

from aenum import Enum


class AddressFamily(str, Enum):
    """
    AddressFamily
    """

    """
    allowed enum values
    """
    UNSPECIFIED = "Unspecified"
    UNIX = "Unix"
    INTERNETWORK = "InterNetwork"
    IMPLINK = "ImpLink"
    PUP = "Pup"
    CHAOS = "Chaos"
    NS = "NS"
    OSI = "Osi"
    ECMA = "Ecma"
    DATAKIT = "DataKit"
    CCITT = "Ccitt"
    SNA = "Sna"
    DECNET = "DecNet"
    DATALINK = "DataLink"
    LAT = "Lat"
    HYPERCHANNEL = "HyperChannel"
    APPLETALK = "AppleTalk"
    NETBIOS = "NetBios"
    VOICEVIEW = "VoiceView"
    FIREFOX = "FireFox"
    BANYAN = "Banyan"
    ATM = "Atm"
    INTERNETWORKV6 = "InterNetworkV6"
    CLUSTER = "Cluster"
    IEEE12844 = "Ieee12844"
    IRDA = "Irda"
    NETWORKDESIGNERS = "NetworkDesigners"
    MAX = "Max"
    PACKET = "Packet"
    CONTROLLERAREANETWORK = "ControllerAreaNetwork"
    UNKNOWN = "Unknown"

    @classmethod
    def from_json(cls, json_str: str) -> AddressFamily:
        """Create an instance of AddressFamily from a JSON string"""
        return AddressFamily(json.loads(json_str))
