# coding: utf-8

"""
    slskd

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Optional

from pydantic import BaseModel, Field, StrictStr, conlist


class BlacklistedOptions(BaseModel):
    """
    Built in blacklisted group options.
    """

    members: Optional[conlist(StrictStr)] = Field(
        None, description="Gets the list of group member usernames."
    )
    __properties = ["members"]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> BlacklistedOptions:
        """Create an instance of BlacklistedOptions from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        # set to None if members (nullable) is None
        # and __fields_set__ contains the field
        if self.members is None and "members" in self.__fields_set__:
            _dict["members"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> BlacklistedOptions:
        """Create an instance of BlacklistedOptions from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return BlacklistedOptions.parse_obj(obj)

        _obj = BlacklistedOptions.parse_obj({"members": obj.get("members")})
        return _obj
