# coding: utf-8

"""
    slskd

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import json
import re  # noqa: F401

from aenum import Enum


class DiagnosticLevel(str, Enum):
    """
    DiagnosticLevel
    """

    """
    allowed enum values
    """
    NONE = "None"
    WARNING = "Warning"
    INFO = "Info"
    DEBUG = "Debug"

    @classmethod
    def from_json(cls, json_str: str) -> DiagnosticLevel:
        """Create an instance of DiagnosticLevel from a JSON string"""
        return DiagnosticLevel(json.loads(json_str))
