# coding: utf-8

"""
    slskd

    A python client for slskd  # noqa: E501

    The version of the OpenAPI document: 0.17.8.0
    Contact: carmine@paolino.me
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import json
import re  # noqa: F401

from aenum import Enum


class FileAttributeType(str, Enum):
    """
    FileAttributeType
    """

    """
    allowed enum values
    """
    BITRATE = "BitRate"
    LENGTH = "Length"
    VARIABLEBITRATE = "VariableBitRate"
    SAMPLERATE = "SampleRate"
    BITDEPTH = "BitDepth"

    @classmethod
    def from_json(cls, json_str: str) -> FileAttributeType:
        """Create an instance of FileAttributeType from a JSON string"""
        return FileAttributeType(json.loads(json_str))
