# coding: utf-8

"""
    slskd

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Optional

from pydantic import BaseModel, Field, conint, constr


class JwtOptions(BaseModel):
    """
    JWT options.
    """

    key: Optional[constr(strict=True, max_length=255, min_length=16)] = Field(
        None, description="Gets the key with which to sign JWTs."
    )
    ttl: Optional[conint(strict=True, le=2147483647, ge=3600)] = Field(
        None, description="Gets the TTL for JWTs, in milliseconds."
    )
    __properties = ["key", "ttl"]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> JwtOptions:
        """Create an instance of JwtOptions from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        # set to None if key (nullable) is None
        # and __fields_set__ contains the field
        if self.key is None and "key" in self.__fields_set__:
            _dict["key"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> JwtOptions:
        """Create an instance of JwtOptions from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return JwtOptions.parse_obj(obj)

        _obj = JwtOptions.parse_obj({"key": obj.get("key"), "ttl": obj.get("ttl")})
        return _obj
