# coding: utf-8

"""
    slskd

    A python client for slskd  # noqa: E501

    The version of the OpenAPI document: 0.17.8.0
    Contact: carmine@paolino.me
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Optional

from pydantic import BaseModel

from slskd.models.threshold_options import ThresholdOptions
from slskd.models.upload_options import UploadOptions


class LeecherOptions(BaseModel):
    """
    Built in leecher group options.
    """

    thresholds: Optional[ThresholdOptions] = None
    upload: Optional[UploadOptions] = None
    __properties = ["thresholds", "upload"]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> LeecherOptions:
        """Create an instance of LeecherOptions from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of thresholds
        if self.thresholds:
            _dict["thresholds"] = self.thresholds.to_dict()
        # override the default output from pydantic by calling `to_dict()` of upload
        if self.upload:
            _dict["upload"] = self.upload.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> LeecherOptions:
        """Create an instance of LeecherOptions from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return LeecherOptions.parse_obj(obj)

        _obj = LeecherOptions.parse_obj(
            {
                "thresholds": ThresholdOptions.from_dict(obj.get("thresholds"))
                if obj.get("thresholds") is not None
                else None,
                "upload": UploadOptions.from_dict(obj.get("upload"))
                if obj.get("upload") is not None
                else None,
            }
        )
        return _obj
