# coding: utf-8

"""
    slskd

    A python client for slskd  # noqa: E501

    The version of the OpenAPI document: 0.17.8.0
    Contact: carmine@paolino.me
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import json
import re  # noqa: F401

from aenum import Enum


class MessageDirection(str, Enum):
    """
    MessageDirection
    """

    """
    allowed enum values
    """
    OUT = "Out"
    IN = "In"

    @classmethod
    def from_json(cls, json_str: str) -> MessageDirection:
        """Create an instance of MessageDirection from a JSON string"""
        return MessageDirection(json.loads(json_str))
