# coding: utf-8

"""
    slskd

    A python client for slskd  # noqa: E501

    The version of the OpenAPI document: 0.17.8.0
    Contact: carmine@paolino.me
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import json
import re  # noqa: F401

from aenum import Enum


class SoulseekClientStates(str, Enum):
    """
    SoulseekClientStates
    """

    """
    allowed enum values
    """
    NONE = "None"
    DISCONNECTED = "Disconnected"
    CONNECTED = "Connected"
    LOGGEDIN = "LoggedIn"
    CONNECTING = "Connecting"
    LOGGINGIN = "LoggingIn"
    DISCONNECTING = "Disconnecting"

    @classmethod
    def from_json(cls, json_str: str) -> SoulseekClientStates:
        """Create an instance of SoulseekClientStates from a JSON string"""
        return SoulseekClientStates(json.loads(json_str))
