# coding: utf-8

"""
    slskd

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import json
import re  # noqa: F401

from aenum import Enum


class TransferStates(str, Enum):
    """
    TransferStates
    """

    """
    allowed enum values
    """
    NONE = "None"
    REQUESTED = "Requested"
    QUEUED = "Queued"
    INITIALIZING = "Initializing"
    INPROGRESS = "InProgress"
    COMPLETED = "Completed"
    SUCCEEDED = "Succeeded"
    CANCELLED = "Cancelled"
    TIMEDOUT = "TimedOut"
    ERRORED = "Errored"
    REJECTED = "Rejected"
    ABORTED = "Aborted"
    LOCALLY = "Locally"
    REMOTELY = "Remotely"

    @classmethod
    def from_json(cls, json_str: str) -> TransferStates:
        """Create an instance of TransferStates from a JSON string"""
        return TransferStates(json.loads(json_str))
