# coding: utf-8

"""
    slskd

    A python client for slskd  # noqa: E501

    The version of the OpenAPI document: 0.17.8.0
    Contact: carmine@paolino.me
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Optional

from pydantic import BaseModel, Field, StrictStr, conlist

from slskd.models.upload_options import UploadOptions


class UserDefinedOptions(BaseModel):
    """
    User defined user group options.
    """

    upload: Optional[UploadOptions] = None
    members: Optional[conlist(StrictStr)] = Field(
        None, description="Gets the list of group member usernames."
    )
    __properties = ["upload", "members"]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> UserDefinedOptions:
        """Create an instance of UserDefinedOptions from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of upload
        if self.upload:
            _dict["upload"] = self.upload.to_dict()
        # set to None if members (nullable) is None
        # and __fields_set__ contains the field
        if self.members is None and "members" in self.__fields_set__:
            _dict["members"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> UserDefinedOptions:
        """Create an instance of UserDefinedOptions from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return UserDefinedOptions.parse_obj(obj)

        _obj = UserDefinedOptions.parse_obj(
            {
                "upload": UploadOptions.from_dict(obj.get("upload"))
                if obj.get("upload") is not None
                else None,
                "members": obj.get("members"),
            }
        )
        return _obj
