# coding: utf-8

"""
    slskd

    A python client for slskd  # noqa: E501

    The version of the OpenAPI document: 0.17.8.0
    Contact: carmine@paolino.me
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import json
import re  # noqa: F401

from aenum import Enum


class UserPresence(str, Enum):
    """
    UserPresence
    """

    """
    allowed enum values
    """
    OFFLINE = "Offline"
    AWAY = "Away"
    ONLINE = "Online"

    @classmethod
    def from_json(cls, json_str: str) -> UserPresence:
        """Create an instance of UserPresence from a JSON string"""
        return UserPresence(json.loads(json_str))
